### PR TITLE
Fixed UI as per review

### LINKED ISSUE #17: Fix UI as per review suggestions

### PR DESCRIPTION
**Pull request by rishabhSharmaOfficial**
Fixes #17

### CODE REVIEW

File: app/javascript/src/components/Common/Sidebar/index.jsx [hunk 1]
```diff
@@ -55,7 +55,7 @@ const Sidebar = () => {
       }}
       profileInfo={{
         name: `${user.first_name} ${user.last_name}`,
-        imageUrl: "https://i.pravatar.cc/300",
+        // imageUrl: "https://i.pravatar.cc/300",
```
Comment (yedhink) [inline app/javascript/src/components/Common/Sidebar/index.jsx:58]: What's the point of pushing a commented code to master? This should've been caught in your self-review.

**Review by yedhink — COMMENTED** [review]
@rishabhSharmaOfficial
